[platformio]
default_envs = pr69_custom

[env]
platform = espressif32@7.0.1
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/m5stack/M5GFX.git#0.2.22
    https://github.com/m5stack/M5Unified.git#0.2.17

[env:main_baseline]
build_flags =
    -DPR69_VARIANT=0
lib_deps =
    ${env.lib_deps}
    https://github.com/m5stack/M5CoreS3.git#adce2225e7fd8d012b148f46c990f8cc7b8ecc26

[env:pr69_default]
build_flags =
    -DPR69_VARIANT=1
lib_deps =
    ${env.lib_deps}
    https://github.com/mhaberler/M5CoreS3.git#c728f1951888aafe57a225069fe71241f6532ff4

[env:pr69_custom]
build_flags =
    -DPR69_VARIANT=2
lib_deps =
    ${env.lib_deps}
    https://github.com/mhaberler/M5CoreS3.git#c728f1951888aafe57a225069fe71241f6532ff4
