[platformio]
default_envs = cores3_usb_host

[env:cores3_usb_host]
platform = espressif32@7.0.1
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/m5stack/M5GFX.git#0.2.22
    https://github.com/m5stack/M5Unified.git#0.2.17
